### ISSUE TITLE
Timeouts for streams?

### ISSUE THREAD

**Issue by StevenACoffman** [stepanstipl/gke-grpc-gateway-api#1]
Hey, I'm using your config (Thanks!), but I'm getting 30s timeouts for any server streams. Do you have any suggestions?

**Comment by StevenACoffman** [comment]
Oh, I figured it out. You need to add a GCPBackendPolicy as in #2 but you have to be careful to specify a namespace for the targetRef or it thinks you mean the default namespace, even when everything else is in another one.

Thanks again for your repo!

**Comment by stepanstipl** [comment]
Hi, glad you figured it out and thanks for the PR - I've merged it, it's useful to have an example how to configure additional properties 👏
